name: Inkeep Source Sync

on:
  push:
    branches:
      - main
    paths:
      - "agents-docs/**"

jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check for changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            docs:
              - 'agents-docs/**'
      - name: Sync Source
        if: steps.changes.outputs.docs == 'true'
        uses: inkeep/pr-commenter-action@bac203359f0328cbb89cca8f9ead7a7176f39a61 # v11
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          apiKey: ${{secrets.INKEEP_API_KEY}}
          sourceId: "cmexes6zq0046s6019sayhjst"